<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Article View' => 'Voir l\'article',
    'Page View' => 'Voir la page',
    '"{attribute}" must be a valid JSON' => '"{attribute}" doit être un JSON valide',
    'Active' => 'Actif',
    'Article ID' => 'Article ID',
    'Author' => 'Auteur',
    'Base URL' => 'Base URL',
    'Base Url' => 'Base Url',
    'Body' => 'Body',
    'Caption' => 'Caption',
    'Carousel ID' => 'Carousel ID',
    'Category' => 'Catégory',
    'Comment' => 'Commentaire',
    'Component' => 'Composant',
    'Config' => 'Configuration',
    'Created At' => 'Crée le',
    'Created at' => 'Crée le',
    'Deleted' => 'Supprimé',
    'Down to maintenance.' => 'Maintenance.',
    'E-mail' => 'E-mail',
    'File Type' => 'Type de fichier',
    'Firstname' => 'Prénom',
    'Gender' => 'Genre',
    'ID' => 'ID',
    'Image' => 'Image',
    'Key' => 'Clé',
    'Last login' => 'Dernier accès',
    'Lastname' => 'Nom',
    'Locale' => 'Locale',
    'Middlename' => 'Deuxième prénom',
    'Name' => 'Nom',
    'Order' => 'Ordre',
    'Other' => 'Autre',
    'Parent Category' => 'Catégorie parente',
    'Path' => 'Chemin',
    'Picture' => 'Image',
    'Published' => 'Publié',
    'Published At' => 'Publié le',
    'Size' => 'Taille',
    'Slug' => 'Slug',
    'Status' => 'Statut',
    'Thumbnail' => 'Miniature',
    'Title' => 'Titre',
    'Type' => 'Type',
    'Updated At' => 'Mis à jour le',
    'Updated at' => 'Mis à jour le',
    'Updater' => 'Оновлено',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'Utilisateur ID',
    'Username' => 'Pseudo',
    'Value' => 'Valeur',
];
