<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Settings' => 'Paramètres du compte',
    'Profile settings' => 'Paramètres du profil',
    'Settings' => 'Paramètres',
    'User Settings' => 'Paramètres de\'utilisateur',
    'About' => 'A propos',
    'Articles' => 'Articles',
    'Attachments' => 'Pièces jointes',
    'Backend' => 'Backend',
    'Body' => 'Body',
    'Check your email for further instructions.' => 'Vérifiez votre email pour d\'autres instructions. ',
    'Confirm Password' => 'Confirmer le mot de passe',
    'Contact' => 'Contact',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Erreur pendant le processus oauth.',
    'Female' => 'Femme',
    'Home' => 'Accueil',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Mot de passe oublié, réinitialisez le <a href="{link}">ici</a>',
    'Incorrect username or password.' => 'Pseudo ou mot de passe incorrecte',
    'Language' => 'Langue',
    'Log in with' => 'Connexion avec',
    'Login' => 'Connexion',
    'Logout' => 'Déconnexion',
    'Male' => 'Homme',
    'Name' => 'Nom',
    'Need an account? Sign up.' => 'Enregistrez-vous',
    'New password was saved.' => 'Nouveau mot de passe sauvegardé',
    'Page not found' => 'Page non trouvée',
    'Password' => 'Mot de passe',
    'Password reset for {name}' => 'Mot de passe réinitialisé pour {name}',
    'Remember Me' => 'Se souvenir de moi',
    'Request password reset' => 'Demande de réinitialisation de mot de passe',
    'Reset password' => 'Réinitialisation de mot de passe',
    'Sign up with' => 'S\'inscrire avec',
    'Signup' => 'Inscription',
    'Sorry, we are unable to reset password for email provided.' => 'Désolé, impossible de réinitialiser le mot de passe pour cet email.',
    'Subject' => 'Sujet',
    'Submit' => 'Envoyer',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Merci. Nous vous répondrons aussi rapidement que possible.',
    'There was an error sending email.' => 'Erreur d\'envoi d\'email',
    'This email address has already been taken.' => 'Adresse e-mail déjà utilisée',
    'This username has already been taken.' => 'Pseudo déjà pris',
    'Update' => 'Mise à jour',
    'Username' => 'Pseudo',
    'Username or email' => 'Pseudo ou e-mail',
    'Verification Code' => 'Code de vérification',
    'We already have a user with email {email}' => 'Nous avons déjà un utilisateur utilisant cet {email}',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Вітаємо . Un e-mail avec vos informations de connexion vous a été envoyé.',
    'Your account has been successfully saved' => 'Votre compte a été sauvegardé avec succès!',
    '{app-name} | Your login information' => '{app-name} | Іnformations de connexion',
];
